### ISSUE TITLE
spams the console with multiples of six

### ISSUE THREAD

**Issue by BartTerpstra1** [SpaceWalkerRS/alternate-current#1]
spams the console with 6,12,18,24,30.
why?!
please make it not spam it in the release versions.

**Comment by SpaceWalkerRS** [comment]
In the latest release I forgot to disable some debugging code that prints the number of block updates that occur each tick in console. That is my mistake and I will make sure future in future releases that code is disabled.

**Comment by srnyx** [comment]
> I will make sure future in future releases that code is disabled.

Took me forever to figure out which mod was causing this (I have around 130 mods on my server). Would be nice if you could make a release soon without this issue (or at least fix it in GitHub and then I can download via GitHub).

**Comment by SpaceWalkerRS** [comment]
I'll close this issue now that there is a release available where it is fixed.
