### ISSUE TITLE
[Question] Where this mod has different behavior than vanilla?

### ISSUE THREAD

**Issue by billy4479** [SpaceWalkerRS/alternate-current#13]
Are there any redstone mechanics that work differently here than they do in vanilla?
How many possibilities are there that this changes would impact my build?

I'm asking this question because on Modrinth you wrote:
> *While Lithium can boast 100% Vanilla parity, Alternate Current cannot.

Is it still a thing or there were changes?

Thank you a lot for your good work on this project :)

**Comment by SpaceWalkerRS** [comment]
Alternate Current changes the update order of redstone dust. So on a surface level, any contraption that relies on redstone dust update order could break or behave differently with AC compared to in Vanilla. In reality, you will notice this in two ways.

Firstly, any contraption that is locational in Vanilla (meaning it behaves differently in different locations, or even breaks in certain locations), will work either everywhere or nowhere with AC. This is by far the biggest difference you will see.

Secondly, there will be contraptions that work (reliably) in Vanilla, but will not work with AC, or contraptions that do not work in Vanilla, but will work with AC. However, you are unlikely to encounter this often unless you are relying heavily on redstone dust update order.

**Comment by billy4479** [comment]
Thank you for the clarification, appreciate your help.
