### ISSUE TITLE
AC break Fabrication colored redstone Function

### ISSUE THREAD

**Issue by ardissaps** [SpaceWalkerRS/alternate-current#17]
This break [Fabrication](https://www.curseforge.com/minecraft/mc-mods/fabrication) "[Colorfur Redstone](https://unascribed.com/fabrication/#mechanics.extra.colorful_redstone)" function.

**Comment by ardissaps** [comment]
https://github.com/unascribed/Fabrication/issues/494

**Comment by unascribed** [comment]
Not an AC bug. It's not reasonable to ask this mod support the bizarre hacky way that Fabrication's Colorful Redstone works.

**Comment by ardissaps** [comment]
Ok I decide disabling colorful redstone wool and install [ChromaticCurrent](https://modrinth.com/mod/chromatic-currents) and [Wired Redstone](https://modrinth.com/mod/wiredredstone) to separate dust line. And keep using AC for regular redstone build. And Fabrication for other tweaks! Thank you for the time and sorry for bothering AC!

**Comment by SpaceWalkerRS** [comment]
No worries! It might as well have been AC's fault, as it does not currently support multiple wire types. It did up until v1.2.1, but even then required a bit of work on the mod author's part to hook into AC's wire handler for power calculations. So it's unlikely any mod that adds new wire blocks is compatible with AC at the moment.
