### ISSUE TITLE
still supporting forge ? (1.20.1)

### ISSUE THREAD

**Issue by DMI-1407** [SpaceWalkerRS/alternate-current#28]
I've seen that forge isn't supported anymore, is this intended ?

**Comment by SpaceWalkerRS** [comment]
The Forge version is not very high on my priority list, so I don't really keep up with when Forge updates. I'll see if I can find some time to update the Forge version some time later this week.

**Comment by SpaceWalkerRS** [comment]
a 1.20 version is now available on Modrinth and CurseForge
