### ISSUE TITLE
1.20.4 Fabric update?

### ISSUE THREAD

**Issue by meyverick** [SpaceWalkerRS/alternate-current#33]
Will you update it for Fabric 1.20.4?

**Comment by donut313** [comment]
the 1.20 version loads in 1.20.4 so I don't see how this is a problem

**Comment by Ristovski** [comment]
Modrinth page is still not updated - https://modrinth.com/mod/alternate-current/versions?g=1.20.4&l=fabric

**Comment by SpaceWalkerRS** [comment]
> Modrinth page is still not updated

Thanks for the message, I updated the last 1.20 release.
