### ISSUE TITLE
Crash On Startup with new version in MC 1.20.1

### ISSUE THREAD

**Issue by NolanHewitt** [SpaceWalkerRS/alternate-current#36]
https://gist.github.com/NolanHewitt/c159b02de92c3de5dc9782a1ede1277c

**Comment by SpaceWalkerRS** [comment]
thanks for the report, fixed in Beta 2!

**Comment by NolanHewitt** [comment]
[crash-2024-05-08_21.32.42-server.txt](https://github.com/SpaceWalkerRS/alternate-current/files/15256855/crash-2024-05-08_21.32.42-server.txt)

I get a different crash now when I load an old world.

**Comment by SpaceWalkerRS** [comment]
Hmm that's annoying. It looks like some of the code for level storage changed somewhere between 1.20.1 and 1.20.4, though I'm not home so I can't tell for sure.

**Comment by SpaceWalkerRS** [comment]
fixed in Beta 3!
