### ISSUE TITLE
Loom 0.8

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [SpaceWalkerRS/alternate-current#4]
Loom 0.8-SNAPSHOT should not be used for Minecraft 1.16 and below because it either breaks compatibility with Java <16 or it fails to comnpile with Java <16 (I forgot which one). Loom 0.8 is essential for Minecraft 1.17 (specifically 21w19a+), but for MC <=1.16, Loom 0.7-SNAPSHOT should be used.

https://github.com/SpaceWalkerRS/alternate-current/blob/b2e4171d809a3ae3c82f657fd54826dae2892cbf/build.gradle#L2

**Comment by SpaceWalkerRS** [comment]
Do you have a source for this? I personally haven't experienced any issues using loom 0.8 on 1.16 and below (I updated RSMM to use loom 0.8 as well).

**Comment by DragonEggBedrockBreaking** [comment]
https://github.com/astei/lazydfu/commit/87b88caae59fd66487460223f03efa0a3ff823a0#commitcomment-51761705

**Comment by SpaceWalkerRS** [comment]
Fixed
