### ISSUE TITLE
Question About AC's Future.

### ISSUE THREAD

**Issue by Luviam** [SpaceWalkerRS/alternate-current#41]
The latest Minecraft snapshot 24w33a has some experimental redstone changes that reduce redstone's impact on performance. And so I ask. Will these new changes that are being introduced invalidate Alternate Current, have no effect, or simply lessen its effectiveness?

**Comment by SpaceWalkerRS** [comment]
I will not make any decisions on Alternate Current's future, at least until the experiments enter the regular snapshot cycle and the changes are finalized.

If you're asking for my thoughts on the latest snapshot specifically, Alternate Current still holds a few advantages. It still holds a performance advantage over Vanilla, though a much lesser one. It doesn't introduce randomness in ambiguous cases, where Vanilla does. And lastly Vanilla skips some important block updates that break a lot of builds. I expect some of these things to be fixed/changed. We'll see over the course of the next snapshot and update cycles.
