### ISSUE TITLE
Observers run slower with alternate-current enabled.

### ISSUE THREAD

**Issue by kaosnightmare** [SpaceWalkerRS/alternate-current#5]
This may not be a very useful report but when testing a lag machine that used redstone updates to lag the game I noticed adding observer ran worse with alternate-current installed as opposed to with it off. It could be due to interactions with other mods or something but I have not looked into it. I can provide more details if needed.

**Comment by SpaceWalkerRS** [comment]
After doing some testing in the latest (not yet released) update, it does seem that observers are affected, though the effect seems fairly minor, a few per cent at most. Is this consistent with your findings? 

I know the source of the performace loss and will look to fix it.

**Comment by kaosnightmare** [comment]
For me it was about 20% increase in TPS for that specific case compared to vanilla but that might be just one specific use case.

**Comment by SpaceWalkerRS** [comment]
That's rather significant. It would help if you could show the specific setup you were using. Which version of the mod are you running currently?

**Comment by kaosnightmare** [comment]
Runnning v0.1.4, also I tested it again and I can't seem reliably reproduce it though so it could have just been coincidence.

**Comment by SpaceWalkerRS** [comment]
This should be fixed in the latest release, so I'll close the issue.
